name: Lint Commit Messages
on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: './commitlint.config.js'
          failOnWarnings: false
          failOnErrors: true
          helpURL: 'https://github.com/conventional-changelog/commitlint/#what-is-commitlint'
